FORMAT: 1A
HOST: https://cc-api.greenmarimba2.com

# cc-iot-app

Critical Climate API is a AWS IoT-based API allowing CC facilities to view/controls its Thrive PLC product.


## Authentication

All requests need to be authenticated, to do this you will need to pass the following in the Header:

> X-API-KEY: Your Api Key

## Devices Collection [/v1/devices]

### Create a New Device [POST]

You may create your own device using this action. It takes a JSON
object containing a device.

+ Request (application/json)


    + Headers
    
            X-API-KEY: api_key

    + Body
 

                {
                    "clientId": "cc",
                    "deviceId": "qa-dredd",
                    "facilityId": "main",
                    "serialNumber": "SN-D7F3C8947867",
                    "devType": "plc",
                    "email": "support@greenmarimba.com"
                }

    + Schema
            
                {
                    "$schema": "http://json-schema.org/draft-04/schema#",
                    "title": "Api Devices - post request schema validator.",
                    "description": "This schema validates POST requests [/v1/devices]",
                    "type": "object",
                    "required": ["clientId","deviceId","facilityId","serialNumber","devType","email"],
                    "properties": {
                      "clientId": {
                        "type": "string",
                        "minLength": 2,
                        "maxLength": 32,
                        "pattern": "^[a-zA-Z0-9:_-]*$"
                      },
                      "facilityId": {
                        "type": "string",
                        "minLength": 4,
                        "maxLength": 32,
                        "pattern": "^[a-zA-Z0-9:_-]*$"
                      },
                      "deviceId": {
                        "type": "string",
                        "minLength": 4,
                        "maxLength": 32,
                        "pattern": "^[a-zA-Z0-9-]*$"
                      },
                      "serialNumber": {
                        "type": "string",
                        "minLength": 4,
                        "maxLength": 32,
                        "pattern": "^[a-zA-Z0-9:_-]*$"
                      },
                      "devType": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 32,
                        "pattern": "^[a-zA-Z0-9]*$"
                      },
                      "email": {
                        "type": "string",
                        "format": "email"
                      }
                    },
                    "additionalProperties": false
                }

+ Response 201 (application/json)

    + Body
 

                {
                    "clientId": "cc",
                    "facilityId": "main",
                    "deviceId": "qa-dredd",
                    "serialNumber": "SN-D7F3C8947867",
                    "activationCode": "AC-9BE75CD0F1543D44C9AB",
                    "activated": false,
                    "email": "support@greenmarimba.com",
                    "endpoint": "endpoint.iot.us-west-2.amazonaws.com",
                    "certs": "s3://cc-iot-devices-us-west-2/devices/certificates/qa-dredd",
                    "topics": {
                        "command": "/cmd/cc/main/qa-dredd",
                        "data": "/dt/cc/main/qa-dredd"
                    }
                }

    + Schema

                {
                    "$schema": "http://json-schema.org/draft-04/schema#",
                    "title": "Api Devices - post response schema validator.",
                    "description": "This schema validates POST requests to the responses [/v1/devices]",
                    "type": "object",
                    "required": [
                      "clientId",
                      "facilityId",
                      "deviceId",
                      "serialNumber",
                      "activationCode",
                      "activated",
                      "email",
                      "endpoint",
                      "certs",
                      "topics"
                    ],
                    "properties": {
                      "clientId": {
                        "type": "string",
                        "minLength": 2,
                        "maxLength": 32,
                        "pattern": "^[a-zA-Z0-9:_-]*$"
                      },
                      "facilityId": {
                        "type": "string",
                        "minLength": 4,
                        "maxLength": 32,
                        "pattern": "^[a-zA-Z0-9:_-]*$"
                      },
                      "deviceId": {
                        "type": "string",
                        "minLength": 4,
                        "maxLength": 32,
                        "pattern": "^[a-zA-Z0-9-]*$"
                      },
                      "serialNumber": {
                        "type": "string",
                        "minLength": 4,
                        "maxLength": 32,
                        "pattern": "^[a-zA-Z0-9:_-]*$"
                      },
                      "activationCode": {
                        "type": "string",
                        "minLength": 4,
                        "maxLength": 23,
                        "pattern": "^[A-Z0-9-]*$"
                      },
                      "activated": {
                        "type": "boolean"
                      },
                      "email": {
                        "type": "string",
                        "format": "email"
                      },
                      "endpoint": {
                        "type": "string",
                        "minLength": 20,
                        "maxLength": 100,
                        "pattern": "^[a-zA-Z0-9:._-]*$"
                      },
                      "certs": {
                        "type": "string",
                        "pattern": "^[a-zA-Z0-9:\/._-]*$"
                      },
                      "topics": {
                        "type": "object",
                        "required": [
                          "command",
                          "data"
                        ],
                        "properties": {
                          "command": {
                            "type": "string"
                          },
                          "data": {
                            "type": "string"
                          }
                        },
                        "additionalProperties": false
                      }
                    },
                    "additionalProperties": false
                }

### Get a device [GET /v1/devices/{deviceId}]

Get JSON struct with the device information.

+ Parameters

    + deviceId: `qa-dredd` (string, required) - The id of the device.
        
+ Response 200 (application/json)

    + Body
 

                {
                    "clientId": "cc",
                    "facilityId": "main",
                    "deviceId": "qa-dredd",
                    "serialNumber": "SN-D7F3C8947867",
                    "activationCode": "AC-9BE75CD0F1543D44C9AB",
                    "activated": false,
                    "email": "support@greenmarimba.com",
                    "endpoint": "endpoint.iot.us-west-2.amazonaws.com",
                    "certs": "s3://cc-iot-devices-us-west-2/devices/certificates/qa-dredd",
                    "topics": {
                        "command": "/cmd/cc/main/qa-dredd",
                        "data": "/dt/cc/main/qa-dredd"
                    }
                }

    + Schema

                {
                    "$schema": "http://json-schema.org/draft-04/schema#",
                    "title": "Api Devices - get response schema validator.",
                    "description": "This schema validates GET requests to the responses [/v1/devices/{deviceId}]",
                    "type": "object",
                    "required": [
                      "clientId",
                      "facilityId",
                      "deviceId",
                      "serialNumber",
                      "activationCode",
                      "activated",
                      "email",
                      "endpoint",
                      "certs",
                      "topics"
                    ],
                    "properties": {
                      "clientId": {
                        "type": "string"
                      },
                      "facilityId": {
                        "type": "string"
                      },
                      "deviceId": {
                        "type": "string"
                      },
                      "serialNumber": {
                        "type": "string"
                      },
                      "activationCode": {
                        "type": "string"
                      },
                      "activated": {
                        "type": "boolean"
                      },
                      "email": {
                        "type": "string"
                      },
                      "endpoint": {
                        "type": "string"
                      },
                      "certs": {
                        "type": "string"
                      },
                      "topics": {
                        "type": "object",
                        "required": [
                          "command",
                          "data"
                        ],
                        "properties": {
                          "command": {
                            "type": "string"
                          },
                          "data": {
                            "type": "string"
                          }
                        },
                        "additionalProperties": false
                      }
                    },
                    "additionalProperties": true
                }

### Delete a Device [DELETE /v1/devices]

Delete a device from the `devices` table as in Iot Core on AWS

+ Request (application/json)

    + Headers
    
            X-API-KEY: api_key

    + Body
 

                {
                    "deviceId": "qa-dredd"
                }

    + Schema

                {
                    "$schema": "http://json-schema.org/draft-04/schema#",
                    "title": "Api Devices - delete schema validator.",
                    "description": "This schema validates DELETE requests [/v1/devices]",
                    "type": "object",
                    "required": ["deviceId"],
                    "properties": {
                       "deviceId": {
                          "type": "string",
                          "minLength": 4, 
                          "maxLength": 32,
                          "pattern": "^[a-zA-Z0-9-]*$"
                       }
                    },
                    "additionalProperties": false
                 }

+ Response 204 (application/json)

### Get device current readings [GET /v1/devices/{deviceId}/readings]

Get current reading from device

+ Parameters 

    + deviceId: `cc-plc` (string, required) - Device ID of the device you want to get current sensor readings from.

+ Response 202 (application/json)

    + Body

                {
                  "Metadata": {
                      "measurements": {
                          "temp": {
                              "unit": "F",
                              "displayname": "Temperature"
                          },
                          "co2": {
                              "unit": "PPM",
                              "displayname": "CO2"
                          },
                          "humidity": {
                              "unit": "%RH",
                              "displayname": "Humidity"
                          },
                          "vpd": {
                              "unit": "kPa",
                              "displayname": "VPD"
                          },
                          "light": {
                              "unit": "%",
                              "displayname": "Light"
                          },
                          "ppfd": {
                              "unit": "PPFD",
                              "displayname": "Light"
                          },
                          "fan": {
                              "unit": "%",
                              "displayname": "Fan"
                          }
                      }
                  },
                  "Data": {
                    "rooms": [
                      {
                        "sensors": {
                          "temp": {
                            "alarm": true,
                            "actual": 32,
                            "setpoint": 75,
                            "maxVal": 90,
                            "minVal": 50
                          },
                          "fan": {
                            "actual": 70,
                            "setpoint": 100
                          },
                          "light": {
                            "actual": 60,
                            "setpoint": 100
                          },
                          "co2": {
                            "alarm": true,
                            "actual": 0,
                            "setpoint": 1200,
                            "maxVal": 1200,
                            "minVal": 100
                          },
                          "humidity": {
                            "alarm": true,
                            "actual": 0,
                            "setpoint": 60,
                            "maxVal": 75,
                            "minVal": 50
                          },
                          "ppfd": {
                            "actual": 0
                          },
                          "vpd": {
                            "alarm": false,
                            "actual": 0.6107800006866455,
                            "maxVal": 1.649999976158142,
                            "minVal": 0.10000000149011612
                          }
                        },
                        "name": "Flower 6",
                        "recipe": {
                          "name": "Strain-A-R200",
                          "recipetime": "Week 3, Day 1, Hour 11",
                          "active": true,
                          "dayMode": true
                        },
                        "maintenanceMode": false,
                        "dayMode": true,
                        "roomId": "flower-6",
                        "notifications": 3
                      }
                    ]
                  },
                  "updatedat": "2020-10-14T18:41:53.659Z"
                }

    + Schema

                {
                    "$schema": "http://json-schema.org/draft-04/schema",
                    "title": "Api Readings - get response schema validator.",
                    "description": "This schema validates GET requests to the responses [/v1/devices/{deviceId}/readings]",
                    "type": "object",
                    "required": [
                      "Metadata",
                      "updatedat",
                      "Data"
                    ],
                    "properties": {
                      "Metadata": {
                        "type": "object",
                        "required": [
                          "measurements"
                        ],
                        "properties": {
                          "measurements": {
                            "type": "object",
                            "required": [
                              "temp",
                              "co2",
                              "humidity",
                              "vpd",
                              "light",
                              "ppfd",
                              "fan"
                            ],
                            "properties": {
                              "temp": {
                                "type": "object",
                                "required": [
                                  "unit",
                                  "displayname"
                                ],
                                "properties": {
                                  "unit": {
                                    "type": "string"
                                  },
                                  "displayname": {
                                    "type": "string"
                                  }
                                },
                                "additionalProperties": false
                              },
                              "co2": {
                                "type": "object",
                                "required": [
                                  "unit",
                                  "displayname"
                                ],
                                "properties": {
                                  "unit": {
                                    "type": "string"
                                  },
                                  "displayname": {
                                    "type": "string"
                                  }
                                },
                                "additionalProperties": false
                              },
                              "humidity": {
                                "type": "object",
                                "required": [
                                  "unit",
                                  "displayname"
                                ],
                                "properties": {
                                  "unit": {
                                    "type": "string"
                                  },
                                  "displayname": {
                                    "type": "string"
                                  }
                                },
                                "additionalProperties": false
                              },
                              "vpd": {
                                "type": "object",
                                "required": [
                                  "unit",
                                  "displayname"
                                ],
                                "properties": {
                                  "unit": {
                                    "type": "string"
                                  },
                                  "displayname": {
                                    "type": "string"
                                  }
                                },
                                "additionalProperties": false
                              },
                              "light": {
                                "type": "object",
                                "required": [
                                  "unit",
                                  "displayname"
                                ],
                                "properties": {
                                  "unit": {
                                    "type": "string"
                                  },
                                  "displayname": {
                                    "type": "string"
                                  }
                                },
                                "additionalProperties": false
                              },
                              "ppfd": {
                                "type": "object",
                                "required": [
                                  "unit",
                                  "displayname"
                                ],
                                "properties": {
                                  "unit": {
                                  "type": "string"
                                  },
                                  "displayname": {
                                    "type": "string"
                                  }
                                },
                                "additionalProperties": false
                              },
                              "fan": {
                                "type": "object",
                                "required": [
                                  "unit",
                                  "displayname"
                                ],
                                "properties": {
                                  "unit": {
                                    "type": "string"
                                  },
                                  "displayname": {
                                    "type": "string"
                                  }
                                },
                                "additionalProperties": false
                              }
                            },
                            "additionalProperties": false
                          }
                        },
                        "additionalProperties": false
                      },
                      "updatedat": {
                        "type": "string"
                      },
                      "Data": {
                        "type": "object",
                        "required": [
                          "rooms"
                        ],
                        "properties": {
                          "rooms": {
                            "type": "array",
                            "additionalItems": true,
                            "items": {
                              "anyOf": [
                                {
                                  "type": "object",
                                  "required": [
                                    "sensors",
                                    "name",
                                    "recipe",
                                    "maintenanceMode",
                                    "dayMode",
                                    "roomId",
                                    "notifications"
                                  ],
                                  "properties": {
                                    "sensors": {
                                      "type": "object",
                                      "required": [
                                        "temp",
                                        "fan",
                                        "light",
                                        "co2",
                                        "humidity",
                                        "ppfd",
                                        "vpd"
                                      ],
                                      "properties": {
                                        "temp": {
                                          "type": "object",
                                          "required": [
                                            "alarm",
                                            "actual",
                                            "setpoint",
                                            "maxVal",
                                            "minVal"
                                          ],
                                          "properties": {
                                            "alarm": {
                                              "type": "boolean"
                                            },
                                            "actual": {
                                              "type": "integer"
                                            },
                                            "setpoint": {
                                              "type": "integer"
                                            },
                                            "maxVal": {
                                              "type": "integer"
                                            },
                                            "minVal": {
                                              "type": "integer"
                                            }
                                          },
                                          "additionalProperties": false
                                        },
                                        "fan": {
                                          "type": "object",
                                          "required": [
                                            "actual",
                                            "setpoint"
                                          ],
                                          "properties": {
                                            "actual": {
                                              "type": "integer"
                                            },
                                            "setpoint": {
                                              "type": "integer"
                                            }
                                          },
                                          "additionalProperties": false
                                        },
                                        "light": {
                                          "type": "object",
                                          "required": [
                                            "actual",
                                            "setpoint"
                                          ],
                                          "properties": {
                                            "actual": {
                                              "type": "integer"
                                            },
                                            "setpoint": {
                                              "type": "integer"
                                            }
                                          },
                                          "additionalProperties": false
                                        },
                                        "co2": {
                                          "type": "object",
                                          "required": [
                                            "alarm",
                                            "actual",
                                            "setpoint",
                                            "maxVal",
                                            "minVal"
                                          ],
                                          "properties": {
                                            "alarm": {
                                              "type": "boolean"
                                            },
                                            "actual": {
                                              "type": "integer"
                                            },
                                            "setpoint": {
                                              "type": "integer"
                                            },
                                            "maxVal": {
                                              "type": "integer"
                                            },
                                            "minVal": {
                                              "type": "integer"
                                            }
                                          },
                                          "additionalProperties": false
                                        },
                                        "humidity": {
                                          "type": "object",
                                          "required": [
                                            "alarm",
                                            "actual",
                                            "setpoint",
                                            "maxVal",
                                            "minVal"
                                          ],
                                          "properties": {
                                            "alarm": {
                                              "type": "boolean"
                                            },
                                            "actual": {
                                              "type": "integer"
                                            },
                                            "setpoint": {
                                              "type": "integer"
                                            },
                                            "maxVal": {
                                              "type": "integer"
                                            },
                                            "minVal": {
                                              "type": "integer"
                                            }
                                          },
                                          "additionalProperties": false
                                        },
                                        "ppfd": {
                                          "type": "object",
                                          "required": [
                                            "actual"
                                          ],
                                          "properties": {
                                            "actual": {
                                              "type": "integer"
                                            }
                                          },
                                          "additionalProperties": false
                                        },
                                        "vpd": {
                                          "type": "object",
                                          "required": [
                                            "alarm",
                                            "actual",
                                            "maxVal",
                                            "minVal"
                                          ],
                                          "properties": {
                                            "alarm": {
                                              "type": "boolean"
                                            },
                                            "actual": {
                                              "type": "number"
                                            },
                                            "maxVal": {
                                              "type": "number"
                                            },
                                            "minVal": {
                                              "type": "number"
                                            }
                                          },
                                          "additionalProperties": false
                                        }
                                      },
                                      "additionalProperties": false
                                    },
                                    "name": {
                                      "type": "string"
                                    },
                                    "recipe": {
                                      "type": "object",
                                      "required": [
                                        "name",
                                        "recipetime",
                                        "active",
                                        "dayMode"
                                      ],
                                      "properties": {
                                        "name": {
                                          "type": "string"
                                        },
                                        "recipetime": {
                                          "type": "string"
                                        },
                                        "active": {
                                          "type": "boolean"
                                        },
                                        "dayMode": {
                                          "type": "boolean"
                                        }
                                      },
                                      "additionalProperties": false
                                    },
                                    "maintenanceMode": {
                                      "type": "boolean"
                                    },
                                    "dayMode": {
                                      "type": "boolean"
                                    },
                                    "roomId": {
                                      "type": "string"
                                    },
                                    "notifications": {
                                      "type": "integer"
                                    }
                                  },
                                  "additionalProperties": false
                                }
                              ]
                            }
                          }
                        },
                        "additionalProperties": false
                      }
                    },
                    "additionalProperties": false
                }

### Rooms Readings [GET /v1/devices/{deviceId}/{roomId}/data{?sensor,start,end,scale}]

Get reading from room

+ Parameters

    + deviceId: `cc-plc` (string, required) - Device ID
    + roomId: `flower-1` (string, required) - Room ID
    + sensor: `temp` (string, required) - All
    + start: `2020-10-01T19:45:42.939Z` (string, required) - All
    + end: `2020-10-13T19:45:42.939Z` (string, required) - All
    + scale: `1min` (string, required) - All
                
+ Response 202 (application/json)
            
    + Body
 

                {
                    "start": "2020-10-01T10:00:00Z",
                    "end": "2020-10-01T13:00:00Z",
                    "period": "5min",
                    "count": 36,
                    "temp": {
                        "actual":   [79,70,73,75,71,76,71,79,73,76,79,75,71,75,78,71,78,71,77,71,77,78,76,74,75,76,75,82,83,83,83,84,84,86,87,88],
                        "setpoint": [75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,78,78,78,78,78,78,78,78,78,78,78],
                        "min":      [70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70],
                        "max":      [82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82]
                    }
                }

    + Schema

                {
                    "$schema": "http://json-schema.org/draft-04/schema",
                    "title": "Api Rooms Readings - get schema validator.",
                    "description": "This schema validates GET requests [/v1/devices/{deviceId}/{roomId}/data{?sensor,start,end,scale}]",
                    "type": "object",
                    "required": [
                        "start",
                        "end",
                        "period",
                        "count",
                        "temp"
                    ],
                    "properties": {
                        "start": {
                            "type": "string"
                        },
                        "end": {
                            "type": "string"
                        },
                        "period": {
                            "type": "string"
                        },
                        "count": {
                            "type": "integer"
                        },
                        "temp": {
                            "type": "object",
                            "required": [
                                "actual",
                                "setpoint",
                                "min",
                                "max"
                            ],
                            "properties": {
                                "actual": {
                                    "type": "array",
                                    "additionalItems": true,
                                    "items": {
                                        "anyOf": [
                                            {
                                                "type": "integer"
                                            }
                                        ]
                                    }
                                },
                                "setpoint": {
                                    "type": "array",
                                    "additionalItems": true,
                                    "items": {
                                        "anyOf": [
                                            {
                                                "type": "integer"
                                            }
                                        ]
                                    }
                                },
                                "min": {
                                    "type": "array",
                                    "additionalItems": true,
                                    "items": {
                                        "anyOf": [
                                            {
                                                "type": "integer"
                                            }
                                        ]
                                    }
                                },
                                "max": {
                                    "type": "array",
                                    "additionalItems": true,
                                    "items": {
                                        "anyOf": [
                                            {
                                                "type": "integer"
                                            }
                                        ]
                                    }
                                }
                            },
                            "additionalProperties": false
                        }
                    },
                    "additionalProperties": false
                }

cierra nueva
