name: Pre-procesado
on:
  push:
    branches: [ master ]
  pull_request:
    branches: 
      - master
      - '**'
jobs: 
  job1: 
    name: Modificando archivos
    runs-on: ubuntu-latest
    steps: 
      - name: Revisar repositorio
        uses: actions/checkout@v2.3.2
      
      - name: Modificando archivos con un script
        run: |
          perl apiary-pre-process.pl

      - name: Listar github
        env:
          GITHUB: ${{ toJson(github) }}
        run: |
          echo "$GITHUB"

      - name: Update files on GitHub
        env:
          BRANCH: ${{ toJson(github.head_ref) }}
        run: |
          git branch -r
          git config --global user.name "pedro-solorzano"
          git config --global user.email "pedro.solorzano@greenmarimba.io"
          git add apiary-test.apib
          git commit -m "apiary-test.apib updated with github actions"
          git push
          