name: Pre-procesado
on: push

jobs: 
  job1: 
    name: Modificando archivos
    runs-on: ubuntu-latest
    steps: 
      - name: Revisar repositorio
        uses: actions/checkout@v2.3.2
      
      - name: Modificando archivos con un script
        run: |
          perl apiary-pre-process.pl

      - name: Update files on GitHub
        uses: test-room-7/action-update-file@v1.4.0
        with: 
          file-path: apiary-test.apib
          commit-msg: apiary pre procesado
          github-token: ${{ secrets.GITHUB_TOKEN }}